### PR TITLE
Restructuring of "Building Content Pages"

### PR DESCRIPTION
**Pull request by jrhoun**
Hey Mike - 

Here's a pull of the article `Building Content Pages`. I kept the initial opening bit because I think it was overall pretty solid and represents the ideal main flow that folks should go through to build a content page.

The rest of the article though got confusing for me with looking at the main flow and then looping out to see a particular Fragment type, and then coming back - and then seeing options for the fragment type. It felt a bit off for me. The restructure is an attempt to organize the article into:

"Building" and "Configuring" sections. And the "Configuring" is organized by the goal / toolbar menu item more so than it is any given fragment type. Part of the reason I organized it this way is because it felt redundant to describe how to add various fragments multiple times and then segway into the optional configurations for them. Instead, I am hoping that it will be obvious how to add any given fragment type - and to shed light on the particular configurations that are available, specifically. Let me know if that doesn't make sense. Thank you for your work on this.

### CODE REVIEW

**Comment by jrhoun** [comment]
Hey @mwilliams2014 just bumping this in case it got lost in the shuffle. Thanks!

**Comment by mwilliams2014** [comment]
It must have. Circling back now. Thanks!

**Comment by mwilliams2014** [comment]
Merged locally. Reviewing now. Thanks!

**Comment by mwilliams2014** [comment]
Updates sent to https://github.com/jrhoun/liferay-learn/pull/225

**Pull request closed without merging**
